# 	NAME: Anchal Goyanka, FNU Shiva Sandesh
# 	EMAIL: anchal.goyanka12344@gmail.com, sandesh.shiva362@gmail.com
# 	ID: 111111111, 111111111
#	Project 3B - CS 111 - Summer 2017
#	target : dependencies

sources = lab3b.py s.sh Makefile README 
all: default
default: 
	@ln -s s.sh lab3b
	@chmod 700 lab3b
clean: 
	@rm -f lab3b lab3b-111111111.tar.gz
dist: 
	tar -zcvf lab3b-1111111111.tar.gz $(sources)
