#       NAME: FNU SHIVA SANDESH
#       EMAIL: sandesh.shiva362@gmail.com
#       ID: 111-111-111
#       Project 1a - CS 111 - Summer 2017

#       target : dependencies
CC = gcc
CFLAGS = -g -Wextra --debug
sources = lab1a.c Makefile README
all: default
default: 
	$(CC) $(CFLAGS) -o lab1a lab1a.c
clean: 
	@rm -f lab1a lab1a-111111111.tar.gz
dist: 
	tar -cf lab1a-111111111.tar.gz $(sources)
