# 	NAME: Anchal Goyanka, FNU Shiva Sandesh
# 	EMAIL: anchal.goyanka12344@gmail.com, sandesh.shiva362@gmail.com
# 	ID: 111111111, 111111111
#	Project 3A - CS 111 - Summer 2017
#	target : dependencies
CC = gcc
CFLAGS = -g -Wextra
sources = lab3a.c Makefile README ext2_fs.h
all: default
default: 
	$(CC) $(CFLAGS) -o lab3a lab3a.c
clean: 
	@rm -f lab3a lab3a-111111111.tar.gz
dist: 
	tar -cf lab3a-111111111.tar.gz $(sources)
